<?php
    get_header();
    get_template_part('templates/home_slider_template');
    get_template_part('templates/about_section_template');
    get_template_part('templates/service_template');
    get_template_part('templates/client_template');
    get_template_part('templates/contact_template');
    get_template_part('templates/team_template');
    get_footer();
?>